// export const data = [
//     {
//       id: "iwfwfw",
//       title:"Portrait in Carnival",
//       url: "https://thumbs.dreamstime.com/b/fantasy-carnival-badajoz-spain-march-performers-costumes-inspired-take-part-parade-comparsas-city-one-141467531.jpg",
//       content:"Performers with costumes inspired in fantasy take part in the Carnival parade of comparsas at Badajoz City. This is one of the best carnivals in Spain, renown by all the national news media and especially highlighting massive participation of people",
//       category:"Celebration",
//       date:"on March 2, 2019.",
//       width: 640,
//       height: 427,
//       related:['Recent','Images','videos','news','Blogs'],
//     },
//     {
//       id: "a2rf24f43",
//       title:"Actors Akshay Kuma and Amy Jackson Bollywood Celebrity India",
//       url: "https://thumbs.dreamstime.com/b/akshay-kumar-amy-jackson-bollywood-celebrity-india-actors-akshay-kumar-ht-gifa-grand-opening-ceremony-event-tau-devi-240342717.jpg",
//       content:"Actors Akshay Kumar and Amy Jackson at the HT GIFA grand opening ceremony event in Tau Devi Lal stadium, in Gurgaon.",
//       category:"Celebration",
//       date:" on September 20, 2015.",
//       width: 700,
//       height: 524,
//     },
//     {
//       id: "a42r4tgrveg",
//       title:"Akshay Kumar and Amy Jackson Bollywood Celebrity India",
//       url: "https://thumbs.dreamstime.com/b/actors-akshay-kumar-amy-jackson-manish-paul-bollywood-celebrity-india-actors-akshay-kumar-amy-jackson-manish-paul-240342877.jpg",
//       content:"Actors Akshay Kumar, at the HT GIFA grand opening ceremony event in Tau Devi Lal stadium, in Gurgaon.",
//       category:"Celebration",
//       date:"on September 20, 2015.",
//       width: 2696,
//       height: 3546,
//     },
//     {
//       id: "35trgfsfra3",
//       title:'NJ - Prabhu Deva and Indian Dancers perform for Donald Trump at Edison New Jersey Hindu Indian-American',
//       url: "https://thumbs.dreamstime.com/b/october-edison-nj-prabhu-deva-indian-dancers-perform-donald-trump-edison-new-jersey-hindu-indian-american-rally-84988823.jpg",
//       content:"NJ - Prabhu Deva and Indian Dancers perform for Donald Trump at Edison New Jersey Hindu Indian-American rally for Humanity United Against Terror",
//       category:"Celebration",
//       date:"on october 15,2016",
//       width: 500,
//       height: 351,
//     },
//     {
//       id: "244444444bhgtrwtrwgg",
//       title:"Actors Akshay Kuma and Amy Jackson Bollywood Celebrity India",
//       url: "https://thumbs.dreamstime.com/b/actors-akshay-kuma-amy-jackson-bollywood-celebrity-india-actors-akshay-kumar-amy-jackson-ht-gifa-grand-opening-240342825.jpg",
//       content:"Actors Akshay Kumar and Amy Jackson at the HT GIFA grand opening ceremony event in Tau Devi Lal stadium, in Gurgaon.",
//       category:"Celebration",      
//       date:"on September 20, 2015.",
//       width: 500,
//       height: 307,
//     },
//   ];
