// export const data = [
//     {
//       id: "cu978iukhjghf",
//       title:"Woman cooking in new kitchen making healthy food with vegetables.",
//       url: "https://thumbs.dreamstime.com/b/woman-cooking-new-kitchen-making-healthy-food-vegetables-diet-concept-49122910.jpg",
//       content:"Woman cooking in new kitchen making healthy food with vegetables. Diet concept",
//       category:"costumes",
//       date:"on March 2, 2019.",
//       width: 1280,
//       height: 956,
//     },
//     {
//       id: "tk9okifhgjhtb",
//       title:"Pouring wine into glass and food",
//       url: "https://thumbs.dreamstime.com/b/pouring-wine-glass-food-28336625.jpg",
//       content:"Pouring wine into glass and food background",
//       category:"Wine",
//       date:"on December 21,2021",
//       width: 500,
//       height: 500,
//     },
//     {
//       id: "gb46uy56hgrewa",
//       title:"Fresh multi fruits splashing into blue clear water splash healthy food diet freshness concept isolated white background",
//       content:"Fresh multi fruits splashing into blue clear water splash healthy food diet freshness concept isolated on white background",
//       category:"Food",
//       date:"on January 31, 2010",
//       url: "https://thumbs.dreamstime.com/z/fresh-multi-fruits-splashing-blue-clear-water-splash-healthy-food-diet-freshness-concept-isolated-white-background-fresh-142771823.jpg",
//       width: 640,
//       height: 428,
//     },
//     {
//       id: "Mfegb454efq324678jgfdf",
//       title:"Food waste",
//       url: "https://thumbs.dreamstime.com/b/food-waste-pile-such-as-eggshells-fruit-vegetable-peels-white-background-51857211.jpg",
//       content:"A pile of food waste, such as eggshells and fruit and vegetable peels, on a white background",
//       category:"Food",
//       date:"on September 30, 2020",
//       width: 450,
//       height: 600,
//     },
//     {
//       id: "Wd_3reg3523wsdy_Mj8",
//       title:"Man throwing leftovers to the trash bin",
//       url: "https://thumbs.dreamstime.com/z/man-throwing-leftovers-to-trash-bin-closeup-young-caucasian-leftover-plate-chickpea-stew-85417262.jpg",
//       content:"Closeup of a young caucasian man throwing the leftover of a plate of chickpea stew to the trash bin ",
//       category:"Wasting Food",
//       date:"on 25 December 2012.",
//       width: 1193,
//       height: 1006,
//     },
//   ];
