export const data = [
    {
      id: "42rfwrr3rg",
      title:'Hollywood actress style',
      url: "https://thumbs.dreamstime.com/z/hollywood-actress-style-vintage-lady-posing-authentic-lighting-57095453.jpg",
      content:"Vintage lady posing with authentic hollywood lighting,Mother giving healthy food to her adorable child at home",
      category:"Hollywood",
      date:"on october 15,2016",
      width: 500,
      height: 351,
    },
    {
      id: "253tgvesg6tg",
      title:"Universal Studios Hollywood Globe in Los Angeles",
      url: "https://thumbs.dreamstime.com/z/universal-studios-hollywood-globe-los-angeles-14844803.jpg",
      content:"Universal Studios Hollywood famous globe at the beginning of the City Walk in Los Angeles California",
      category:"Hollywood",      
      date:"on September 20, 2015.",
      width: 500,
      height: 307,
    },
    {
      id: "cu978iukhjghf",
      title:"Rade Serbedzija, Danilo Serbedzija, 22nd Sarajevo Film Festival, The Liberation of Skopje",
      url: "https://thumbs.dreamstime.com/z/rade-serbedzija-danilo-serbedzija-nd-sarajevo-film-festival-liberation-skopje-presenting-their-new-filmed-75743089.jpg",
      content:"Rade and Danilo Serbedzija presenting their new film The Liberation of Skopje at Sarajevo Film Festival. Filmed at Sarajevo during the Avant Premiere Press Junket. Date: August 13th 2016, time around 19.00. Rade Serbedzija is a famous actor who acted in several Hollywood films, as well as many films made in Former Yugoslavia. He is also a film director. His son Danilo Serbedzija is a film director.",
      category:"Hollywood",
      date:"on March 2, 2019.",
      width: 1280,
      height: 956,
    },
    {
      id: "tk9okifhgjhtb",
      title:"Movie Film Crew on location RIPD movie",
      url: "https://thumbs.dreamstime.com/z/movie-film-crew-location-21618695.jpg",
      content:"Peter M. Lenkov (seated) producer and writer of the upcoming Jeff Bridges and Ryan Reynolds graphic novel movie R. I. P. D. about zombie police set to be released in 2013, filming in downtown Boston on Oct. 15, 2011. Directed by Robert Schwentke. Starring: Ryan Reynolds, Jeff Bridges, Kevin Bacon, Stephanie Szostak, Mary-Louise Parker, Marisa Miller, Mike OMalley, James Hong, Robert Knepper",
      category:"Hollywood",
      date:"on December 21,2021",
      width: 500,
      height: 500,
    },
    {
      id: "Wd_3reg3523wsdy_Mj8",
      title:"Galaxy`s Edge, Disney World, Hollywood Studios",
      url: "https://thumbs.dreamstime.com/z/galaxy-s-edge-disney-world-hollywood-studios-wall-poster-conceptual-design-new-star-wars-section-walt-orlando-141315570.jpg",
      content:"Wall poster with a conceptual design of the new Galaxy`s Edge Star Wars section of Hollywood Studios at Walt Disney World in Orlando, FL. Florida is a popular travel destination for people and tourists who travel on vacation or holiday.",
      category:"Hollywood",
      date:"on 25 December 2012.",
      width: 1193,
      height: 1006,
    },
  ];