export const data = [
    {
      id: "iwfwfw",
      title:"Portrait in Carnival",
      url: "https://thumbs.dreamstime.com/b/fantasy-carnival-badajoz-spain-march-performers-costumes-inspired-take-part-parade-comparsas-city-one-141467531.jpg",
      content:"Performers with costumes inspired in fantasy take part in the Carnival parade of comparsas at Badajoz City. This is one of the best carnivals in Spain, renown by all the national news media and especially highlighting massive participation of people",
      category:"Celebration",
      date:"on March 2, 2019.",
      width: 640,
      height: 427,
      related:['Recent','Images','videos','news','Blogs'],
    },
    {
      id: "tk9okifhgjhtb",
      title:"Pouring wine into glass and food",
      url: "https://thumbs.dreamstime.com/b/pouring-wine-glass-food-28336625.jpg",
      content:"Pouring wine into glass and food background",
      category:"Wine",
      date:"on December 21,2021",
      width: 500,
      height: 500,
    },
    {
        id: "edpwf343ffcvjmkfdbthet",
        title:"Flat icons technology, social media, network, computer concept. Abstract background with objects group of elements. star smiley",
        content:"Flat icons technology, social media, network, computer concept. Abstract background with objects with group of elements. star smiley face sale. Share, Like, Comment, Vector illustration Twitter, YouTube, WhatsApp, Snapchat, Facebook, instagram",
        category:"Technology",
        date:"on January 31, 2010",
        url: "https://thumbs.dreamstime.com/z/flat-icons-technology-social-media-network-computer-concept-abstract-background-objects-group-elements-star-smiley-f-flat-114450116.jpg",
        width: 640,
        height: 428,
      },
    {
      id: "35trgfsfra3",
      title:'NJ - Prabhu Deva and Indian Dancers perform for Donald Trump at Edison New Jersey Hindu Indian-American',
      url: "https://thumbs.dreamstime.com/b/october-edison-nj-prabhu-deva-indian-dancers-perform-donald-trump-edison-new-jersey-hindu-indian-american-rally-84988823.jpg",
      content:"NJ - Prabhu Deva and Indian Dancers perform for Donald Trump at Edison New Jersey Hindu Indian-American rally for Humanity United Against Terror",
      category:"Celebration",
      date:"on october 15,2016",
      width: 500,
      height: 351,
    },
    
    {
      id: "244444444bhgtrwtrwgg",
      title:"Actors Akshay Kuma and Amy Jackson Bollywood Celebrity India",
      url: "https://thumbs.dreamstime.com/b/actors-akshay-kuma-amy-jackson-bollywood-celebrity-india-actors-akshay-kumar-amy-jackson-ht-gifa-grand-opening-240342825.jpg",
      content:"Actors Akshay Kumar and Amy Jackson at the HT GIFA grand opening ceremony event in Tau Devi Lal stadium, in Gurgaon.",
      category:"Celebration",      
      date:"on September 20, 2015.",
      width: 500,
      height: 307,
    },
    {
        id: "Wd_3reg3523wsdy_Mj8",
        title:"Galaxy`s Edge, Disney World, Hollywood Studios",
        url: "https://thumbs.dreamstime.com/z/galaxy-s-edge-disney-world-hollywood-studios-wall-poster-conceptual-design-new-star-wars-section-walt-orlando-141315570.jpg",
        content:"Wall poster with a conceptual design of the new Galaxy`s Edge Star Wars section of Hollywood Studios at Walt Disney World in Orlando, FL. Florida is a popular travel destination for people and tourists who travel on vacation or holiday.",
        category:"Hollywood",
        date:"on 25 December 2012.",
        width: 1193,
        height: 1006,
      },
      {
        id: "35trgfqecdsdnsfra3",
        title:'Working out at home with online fitness course, workout video or personal trainer service in phone. Health or sport mobile app.',
        url: "https://thumbs.dreamstime.com/z/working-out-home-online-fitness-course-workout-video-personal-trainer-service-phone-health-sport-mobile-app-144081381.jpg",
        content:"Working out at home with online fitness course, workout video or personal trainer service in phone. Health or sport mobile app in cellphone. Fit woman with smartphone and gym equipment",
        category:"Gym",
        date:"on october 15,2016",
        width: 500,
        height: 351,
      },
  ];
