export const data = [
    {
      id: "iwfwfw",
      title:"Portrait in Carnival",
      url: "https://thumbs.dreamstime.com/b/fantasy-carnival-badajoz-spain-march-performers-costumes-inspired-take-part-parade-comparsas-city-one-141467531.jpg",
      content:"Performers with costumes inspired in fantasy take part in the Carnival parade of comparsas at Badajoz City. This is one of the best carnivals in Spain, renown by all the national news media and especially highlighting massive participation of people",
      category:"Celebration",
      date:"on March 2, 2019.",
      width: 640,
      height: 427,
      related:['Recent','Images','videos','news','Blogs'],
    },
    {
      id: "a2rf24f43",
      title:"Actors Akshay Kuma and Amy Jackson Bollywood Celebrity India",
      url: "https://thumbs.dreamstime.com/b/akshay-kumar-amy-jackson-bollywood-celebrity-india-actors-akshay-kumar-ht-gifa-grand-opening-ceremony-event-tau-devi-240342717.jpg",
      content:"Actors Akshay Kumar and Amy Jackson at the HT GIFA grand opening ceremony event in Tau Devi Lal stadium, in Gurgaon.",
      category:"Celebration",
      date:" on September 20, 2015.",
      width: 700,
      height: 524,
    },
    {
      id: "a42r4tgrveg",
      title:"Akshay Kumar and Amy Jackson Bollywood Celebrity India",
      url: "https://thumbs.dreamstime.com/b/actors-akshay-kumar-amy-jackson-manish-paul-bollywood-celebrity-india-actors-akshay-kumar-amy-jackson-manish-paul-240342877.jpg",
      content:"Actors Akshay Kumar, at the HT GIFA grand opening ceremony event in Tau Devi Lal stadium, in Gurgaon.",
      category:"Celebration",
      date:"on September 20, 2015.",
      width: 2696,
      height: 3546,
    },
    {
      id: "35trgfsfra3",
      title:'NJ - Prabhu Deva and Indian Dancers perform for Donald Trump at Edison New Jersey Hindu Indian-American',
      url: "https://thumbs.dreamstime.com/b/october-edison-nj-prabhu-deva-indian-dancers-perform-donald-trump-edison-new-jersey-hindu-indian-american-rally-84988823.jpg",
      content:"NJ - Prabhu Deva and Indian Dancers perform for Donald Trump at Edison New Jersey Hindu Indian-American rally for Humanity United Against Terror",
      category:"Celebration",
      date:"on october 15,2016",
      width: 500,
      height: 351,
    },
    {
      id: "244444444bhgtrwtrwgg",
      title:"Actors Akshay Kuma and Amy Jackson Bollywood Celebrity India",
      url: "https://thumbs.dreamstime.com/b/actors-akshay-kuma-amy-jackson-bollywood-celebrity-india-actors-akshay-kumar-amy-jackson-ht-gifa-grand-opening-240342825.jpg",
      content:"Actors Akshay Kumar and Amy Jackson at the HT GIFA grand opening ceremony event in Tau Devi Lal stadium, in Gurgaon.",
      category:"Celebration",      
      date:"on September 20, 2015.",
      width: 500,
      height: 307,
    },
    {
      id: "cw34r4222dadm5",
      title:"Egyptian costumes in carnival parade",
      url: "https://thumbs.dreamstime.com/b/masks-ancient-egypt-carnival-parade-badajoz-spain-march-performers-costumes-inspired-ancient-egypt-take-part-142003482.jpg",
      content:"Performers with costumes inspired in Egyptian take part in the Carnival parade of comparsas at Badajoz City. This is one of the best carnivals in Spain, renown by all the national news media and especially highlighting massive participation of people",
      category:"costumes",
      date:"on March 2, 2019.",
      width: 1280,
      height: 956,
    },
    {
      id: "teht7900ugukfhd5s",
      title:"Bollywood star Shahrukh khan with fans",
      url: "https://thumbs.dreamstime.com/b/bollywood-star-shahrukh-khan-showing-gratitude-to-his-fans-bhopal-bollywood-star-shahrukh-khan-fans-131126290.jpg",
      content:"Bollywood star Shahrukh khan showing gratitude to his fans in Bhopal",
      category:"Stage Perfomance",
      date:"on December 21,2021",
      width: 500,
      height: 500,
    },
    {
      id: "edp23223edfcvfdbthet",
      title:"Indian Music and Dance Show",
      content:"The Indian Bollywood Film Star Song and Dance Troupe perform on stage during Indian Music and Dance Show at Beijing Exhibition Theater on January 31, 2010 in Beijing, China. The Indian Bollywood Film Star Song and Dance Troupe stage Indian pop songs and dance scenes from classic Bollywood films, including Rhythm of Love, Jaane Kisne, and Overjoyed Rhythm.",
      category:"Dance",
      date:"on January 31, 2010",
      url: "https://thumbs.dreamstime.com/b/indian-music-dance-show-12799791.jpg",
      width: 640,
      height: 428,
    },
    {
      id: "M4rrfdfgtgt667543TUyNzY4Mw",
      title:"Baggage carrier at the Mumbai Railway station",
      url: "https://thumbs.dreamstime.com/b/baggage-carrier-mumbai-railway-station-16230466.jpg",
      content:"Cool people these baggage carriers as they find their way trough the enormously crowed platforms at Victoria Station in Mumbai to deliver the baggage at your place.",
      category:"Workers",
      date:"on September 30, 2020",
      width: 450,
      height: 600,
    },
    {
      id: "Wd_3114124teghbvcPy_Mj8",
      title:"Classic Film Poster",
      url: "https://thumbs.dreamstime.com/b/classic-film-poster-28374714.jpg",
      content:"Classic Indian Bollywood movie poster. Photo was taken in Singapore National Museum. ",
      category:"Museum",
      date:"on 25 December 2012.",
      width: 1193,
      height: 1006,
    },
  ];
