export const data = [
    {
      id: "iwfwfw2ew",
      title:"Healthy lifestyle fitness sports woman running",
      url: "https://thumbs.dreamstime.com/z/healthy-lifestyle-fitness-sports-woman-running-sunrise-road-39709089.jpg",
      content:"Healthy lifestyle fitness sports woman running at sunrise road",
      category:"Fitness",
      date:"on March 2, 2019.",
      width: 640,
      height: 427,
    },
    {
      id: "a2r32rqef24f43",
      title:"Close up hands. Woman do yoga outdoor",
      url: "https://thumbs.dreamstime.com/z/close-up-hands-woman-do-yoga-outdoor-woman-exercising-vital-meditation-fitness-lifestyle-beach-sunset-background-104776221.jpg",
      content:"Close up hands. Woman do yoga outdoor. Woman exercising vital and meditation for fitness lifestyle in the beach sunset background. Healthy Concept",
      category:"Yoga",
      date:" on September 20, 2015.",
      width: 700,
      height: 524,
    },
    {
      id: "a42qedqr4tgrveg",
      title:"Invest in your health, Healthy lifestyle concept with diet and fitness, Get fit in, fitness equipment and healthy food",
      url: "https://thumbs.dreamstime.com/z/invest-your-health-healthy-lifestyle-concept-diet-fitness-get-fit-fitness-equipment-healthy-food-invest-your-158227197.jpg",
      content:"Invest in your health , Healthy lifestyle concept with diet and fitness , Get fit in , fitness equipment and healthy food ",
      category:"healthy Food",
      date:"on September 20, 2015.",
      width: 2696,
      height: 3546,
    },
    {
      id: "35trgfqecdsdnsfra3",
      title:'Working out at home with online fitness course, workout video or personal trainer service in phone. Health or sport mobile app.',
      url: "https://thumbs.dreamstime.com/z/working-out-home-online-fitness-course-workout-video-personal-trainer-service-phone-health-sport-mobile-app-144081381.jpg",
      content:"Working out at home with online fitness course, workout video or personal trainer service in phone. Health or sport mobile app in cellphone. Fit woman with smartphone and gym equipment",
      category:"Gym",
      date:"on october 15,2016",
      width: 500,
      height: 351,
    },
    {
      id: "trgf444bhgtrwtrwgg",
      title:"Sports nutrition and fitness equipment.",
      url: "https://thumbs.dreamstime.com/z/sports-nutrition-fitness-equipment-sports-nutrition-supplements-healthy-food-dumbbells-black-background-fitness-112716854.jpg",
      content:"Sports nutrition supplements, healthy food and dumbbells on a black background. Fitness, bodybuilding, sport and healthy lifestyle concept.",
      category:"Celebration",      
      date:"on September 20, 2015.",
      width: 500,
      height: 307,
    },
    {
      id: "cwaww334r4222dadm5",
      title:"FITNESS",
      url: "https://thumbs.dreamstime.com/z/fitness-word-cloud-sport-health-concept-58066979.jpg",
      content:"FITNESS word cloud, sport, health concept",
      category:"Fitness",
      date:"on March 2, 2019.",
      width: 1280,
      height: 956,
    },
    {
      id: "t23ddeht7900ugukfhd5s",
      title:"Asian fitness woman runner stretching legs before run outdoor workout in the park.",
      url: "https://thumbs.dreamstime.com/z/asian-fitness-woman-runner-stretching-legs-run-outdoor-workout-park-healthy-concept-106427114.jpg",
      content:"Asian fitness woman runner stretching legs before run outdoor workout in the park. Healthy Concept.",
      category:"warmUp",
      date:"on December 21,2021",
      width: 500,
      height: 500,
    },
    {
      id: "a2r32rqef24f43",
      title:"Close up hands. Woman do yoga outdoor",
      url: "https://thumbs.dreamstime.com/z/close-up-hands-woman-do-yoga-outdoor-woman-exercising-vital-meditation-fitness-lifestyle-beach-sunset-background-104776221.jpg",
      content:"Close up hands. Woman do yoga outdoor. Woman exercising vital and meditation for fitness lifestyle in the beach sunset background. Healthy Concept",
      category:"Yoga",
      date:" on September 20, 2015.",
      width: 700,
      height: 524,
    },
    {
      id: "a42qedqr4tgrveg",
      title:"Invest in your health, Healthy lifestyle concept with diet and fitness, Get fit in, fitness equipment and healthy food",
      url: "https://thumbs.dreamstime.com/z/invest-your-health-healthy-lifestyle-concept-diet-fitness-get-fit-fitness-equipment-healthy-food-invest-your-158227197.jpg",
      content:"Invest in your health , Healthy lifestyle concept with diet and fitness , Get fit in , fitness equipment and healthy food ",
      category:"healthy Food",
      date:"on September 20, 2015.",
      width: 2696,
      height: 3546,
    },
    {
      id: "35trgfqecdsdnsfra3",
      title:'Working out at home with online fitness course, workout video or personal trainer service in phone. Health or sport mobile app.',
      url: "https://thumbs.dreamstime.com/z/working-out-home-online-fitness-course-workout-video-personal-trainer-service-phone-health-sport-mobile-app-144081381.jpg",
      content:"Working out at home with online fitness course, workout video or personal trainer service in phone. Health or sport mobile app in cellphone. Fit woman with smartphone and gym equipment",
      category:"Gym",
      date:"on october 15,2016",
      width: 500,
      height: 351,
    },
    {
      id: "iwfwfw2ew",
      title:"Healthy lifestyle fitness sports woman running",
      url: "https://thumbs.dreamstime.com/z/healthy-lifestyle-fitness-sports-woman-running-sunrise-road-39709089.jpg",
      content:"Healthy lifestyle fitness sports woman running at sunrise road",
      category:"Fitness",
      date:"on March 2, 2019.",
      width: 640,
      height: 427,
    },
  ];
  