export const data = [
    {
      id: "wf343ffwfw",
      title:"TOKYO JAPAN - APR 16, 2018 :Pepper Robot Assistant Information touch screen Humanoid technology communicate with people in Tokyo",
      url: "https://thumbs.dreamstime.com/z/tokyo-japan-apr-pepper-robot-assistant-information-touch-screen-humanoid-technology-communicate-people-tokyo-j-tokyo-japan-125493405.jpg",
      content:"TOKYO JAPAN - APR 16, 2018 :Pepper Robot Assistant Information touch screen Humanoid technology communicate with people in Tokyo Japan",
      date:"on March 2, 2019.",
      category:"Technology",
      width: 640,
      height: 427,
      related:['Recent','Images','videos','news','Blogs'],
    },
    {
      id: "awf343fr4f43",
      title:"Online Reviews Evaluation Concept with computer halogram scanning on data of business and all technology",
      url: "https://thumbs.dreamstime.com/z/online-reviews-evaluation-concept-computer-halogram-scanning-data-business-all-new-technology-online-reviews-108907268.jpg",
      content:"Online Reviews Evaluation Concept with computer halogram scanning on data of business and all new technology",
      category:"Technology",
      date:" on September 20, 2015.",
      width: 700,
      height: 524,
    },
    {
      id:"wf343f2r4t564tgrveg",
      title:"Online Reviews Evaluation Concept with computer halogram scanning on data of business and all new technology",
      url: "https://thumbs.dreamstime.com/z/business-woman-drawing-global-structure-networking-business-woman-drawing-global-structure-networking-data-exchanges-customer-109179483.jpg",
      content:"Business woman drawing global structure networking and data exchanges customer connection on dark background",
      category:"Technology",
      date:"on September 20, 2015.",
      width: 2696,
      height: 3546,
    },
    {
      id:"wf343fgfsfrhrra3",
      title:'Sustainable development, eco friendly lifestyle concept. 3d rend',
      url: "https://thumbs.dreamstime.com/z/sustainable-development-eco-friendly-lifestyle-concept-d-rend-sustainable-development-eco-friendly-lifestyle-concept-d-rendering-116932229.jpg",
      content:"Sustainable development, eco friendly lifestyle concept. 3d rendering of arrow circle icon on fresh spring meadow with blue sky in background.",
      category:"Technology",
      date:"on october 15,2016",
      width: 500,
      height: 351,
    },
    {
      id:"wf343f44444bhgtrwtrjuwgg",
      title:"Technology fair and exhibition in China",
      url: "https://thumbs.dreamstime.com/z/technology-fair-exhibition-china-23697237.jpg",
      content:"A Technology fair about semi-conductor and integration circle industry in Guangdong, China.",
      category:"Technology",      
      date:"on September 20, 2015.",
      width: 500,
      height: 307,
    },
    {
      id: "wf343f222dadm5",
      title:"Laboratory Test Tube in Science Research Lab",
      url: "https://thumbs.dreamstime.com/z/laboratory-test-tube-science-research-lab-5569187.jpg",
      content:"Scientist hand holding a laboratory glass test tube filled with yellow liquid for an experiment in a science research lab",
      category:"Technology",
      date:"on March 2, 2019.",
      width: 1280,
      height: 956,
    },
    {
      id: "tewf343fgugmkfhd5s",
      title:"Laboratory",
      url: "https://thumbs.dreamstime.com/z/laboratory-18359431.jpg",
      content:"Scientists working at the laboratory",
      category:"Technology",
      date:"on December 21,2021",
      width: 500,
      height: 500,
    },
    {
      id: "edpwf343ffcvjmkfdbthet",
      title:"Flat icons technology, social media, network, computer concept. Abstract background with objects group of elements. star smiley",
      content:"Flat icons technology, social media, network, computer concept. Abstract background with objects with group of elements. star smiley face sale. Share, Like, Comment, Vector illustration Twitter, YouTube, WhatsApp, Snapchat, Facebook, instagram",
      category:"Technology",
      date:"on January 31, 2010",
      url: "https://thumbs.dreamstime.com/z/flat-icons-technology-social-media-network-computer-concept-abstract-background-objects-group-elements-star-smiley-f-flat-114450116.jpg",
      width: 640,
      height: 428,
    },
    {
      id: "M4rrfdfgwf343f43hklTUyNzY4Mw",
      title:"Collection of old audio cassette tapes isolated on white background vintage music and technology concept",
      url: "https://thumbs.dreamstime.com/z/collection-old-audio-cassette-tapes-isolated-white-background-vintage-music-technology-concept-189782689.jpg",
      content:"Collection of old audio cassette tapes isolated on white background, vintage music and technology concept",
      category:"Technology",
      date:"on September 30, 2020",
      width: 450,
      height: 600,
    },
    {
      id: "Wd_311412wf343fjkhgfbvcPy_Mj8",
      title:"Grabbing money",
      url: "https://thumbs.dreamstime.com/z/grabbing-money-18095541.jpg",
      content:"Grabbing money isolated on white background ",
      category:"Technology",
      date:"on 25 December 2012.",
      width: 1193,
      height: 1006,
    },
  ];
